<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); \r\n      <li><a href=\"news_text.html\" target=\"_blank\"><span class=\"xwtp\"><img src='{@me['litpic']}'/></span><span class=\"title\">[field:title",5,286);
$z[0][4]['runphp']="yes";
$z[1]=Array("description","",362,382);
$z[2]=Array("description","",398,418);

?>