<?php
$z[0]=Array("field","",1968,1987);
$z[0][4]['name']="title";
$z[1]=Array("field","",2011,2067);
$z[1][4]['name']="pubdate";
$z[1][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[2]=Array("field","",2110,2137);
$z[2][4]['name']="phpurl";
$z[3]=Array("field","",2161,2184);
$z[3][4]['name']="id";
$z[4]=Array("field","",2189,2213);
$z[4][4]['name']="mid";
$z[5]=Array("field","",2308,2326);
$z[5][4]['name']="body";
$z[6]=Array("prenext","",2392,2417);
$z[6][4]['get']="pre";
$z[7]=Array("prenext","",2436,2462);
$z[7][4]['get']="next";

?>