<div class="Public">
        <div class="Public-box-news">
                <div class="Proxy-news">
                    <a href="/site/article?id=10" style="background:url({@me['litpic']}) no-repeat 0 0; display:block;">
                        <img src="http://stc.weimob.com/img/www/index1/news-bg.png" name="image1" onmouseover="this.style.opacity=1;" onmouseout="this.style.opacity=0;" style="opacity: 0;">
                    </a>
                    <h3>[field:title/]</h3>
                    <p>[field:description/]... </p>
                </div>
            </div>