<?php
$z[0]=Array("arclist","\r\n      <li><a href=\"news.html\" target=\"_blank\"><span class=\"tp\">[field:array runphp='yes' ]@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'width='80px' height='60px'/>\" ); [/field:array]</span><span class=\"tit\">[field:title/]</span><span class=\"nr1\">\r\n        <script>document.write(csubstr(\"[field:description/]\",45));</script>\r\n        </span></a></li>",7780,8201);
$z[0][4]['row']="2";
$z[0][4]['titlelen']="48";

?>