<?php
$z[0]=Array("list","<li>\r\n    \r\n       <a href=\"[field:arcurl/]\" target=\"_blank\"><span class=\"xwtp\">[field:array runphp='yes' ]@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'width='120px' height='85px'/>\" ); [/field:array]</span><span class=\"title\">[field:title/]</span>\r\n      <span class=\"xwnr\">\r\n        <script>document.write(csubstr(\"[field:description/]\",));</script>[field:description/]...\r\n</li>",2098,2534);
$z[0][4]['pagesize']="10";

?>